"""Team defense definitions.

What the defense allowed and the plays it made.

One part of the team registry that `team_metrics.TEAM_METRICS` assembles in catalog order;
human-readable companion: [docs/stats-catalog.md](../../docs/stats-catalog.md).
"""

from __future__ import annotations

from nfl_sos_ratings.metrics.schema import MetricDef, section

_def_total = section("team", "Defense", "Total")
_def_pass = section("team", "Defense", "Passing")
_def_rush = section("team", "Defense", "Rushing")
_def_recv = section("team", "Defense", "Receiving")
_def_score = section("team", "Defense", "Scoring")
_def_downs = section("team", "Defense", "Downs & Conversions")
_def_drives = section("team", "Defense", "Drives & Field Position")
_def_to = section("team", "Defense", "Turnovers")
_def_press = section("team", "Defense", "Pressure & Playmaking")
_def_pen = section("team", "Defense", "Penalties")

_TARGETS_GAP_NOTE = (
    "Blank in 2003-2008, when nflverse play-by-play names the intended receiver on almost no "
    "incomplete passes."
)

DEFENSE_METRICS: tuple[MetricDef, ...] = (
    _def_total(
        name="defensive_snaps",
        label="Def Snaps",
        full_name="Defensive Snaps",
        description=(
            "Scrimmage plays the defense was on the field for. The denominator for "
            "per-defensive-snap rates."
        ),
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _def_total(
        name="total_yards_allowed",
        label="Total Yds Allowed",
        full_name="Total Yards Allowed",
        description="Passing plus rushing yards given up by the defense.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
        note="Sums the two allowed yardage stats.",
    ),
    _def_pass(
        name="passing_yards_allowed",
        label="Pass Yds Allowed",
        full_name="Passing Yards Allowed",
        description="Gross passing yards given up through the air.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="passing_epa_allowed",
        label="Pass EPA Allowed",
        full_name="Passing EPA Allowed",
        description=(
            "Expected points added that opposing passing games generated. Negative means "
            "the defense beat an average passing offense."
        ),
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="passing_tds_allowed",
        label="Pass TDs Allowed",
        full_name="Passing Touchdowns Allowed",
        description="Touchdown passes given up.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="passing_first_downs_allowed",
        label="Pass 1Ds Allowed",
        full_name="Passing First Downs Allowed",
        description="First downs given up through the air.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="passing_cpoe_allowed",
        label="CPOE Allowed",
        full_name="Completion Percentage Above Expectation Allowed",
        description=(
            "How much more accurately opponents completed passes than the difficulty of "
            "their throws would predict. Negative means the coverage forced misses."
        ),
        shape="avg",
        polarity="lower",
        source="PBP +TS",
        denominator="opponent pass attempts (model-expected completions)",
        since=2006,
    ),
    _def_rush(
        name="rushing_yards_allowed",
        label="Rush Yds Allowed",
        full_name="Rushing Yards Allowed",
        description="Rushing yards given up on the ground.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_rush(
        name="rushing_epa_allowed",
        label="Rush EPA Allowed",
        full_name="Rushing EPA Allowed",
        description="Expected points added that opposing running games generated.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_rush(
        name="rushing_tds_allowed",
        label="Rush TDs Allowed",
        full_name="Rushing Touchdowns Allowed",
        description="Rushing touchdowns given up.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_rush(
        name="rushing_first_downs_allowed",
        label="Rush 1Ds Allowed",
        full_name="Rushing First Downs Allowed",
        description="First downs given up on the ground.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_press(
        name="def_sacks",
        label="Def Sacks",
        full_name="Defensive Sacks",
        description="Times the defense sacked the opposing quarterback.",
        shape="count",
        polarity="higher",
        source="PLS",
        since=1999,
    ),
    _def_press(
        name="def_qb_hits",
        label="Def QB Hits",
        full_name="Defensive QB Hits",
        description="Times the defense hit the quarterback, beyond sacks.",
        shape="count",
        polarity="higher",
        source="PLS",
        since=1999,
    ),
    _def_press(
        name="def_tackles_for_loss",
        label="Def TFL",
        full_name="Defensive Tackles for Loss",
        description="Tackles made behind the line of scrimmage.",
        shape="count",
        polarity="higher",
        source="PLS",
        since=1999,
    ),
    _def_press(
        name="def_pass_defended",
        label="Def PD",
        full_name="Passes Defended",
        description="Passes broken up or deflected by defenders.",
        shape="count",
        polarity="higher",
        source="PLS",
        since=1999,
    ),
    _def_press(
        name="def_fumbles_forced",
        label="Def FF",
        full_name="Defensive Fumbles Forced",
        description="Fumbles the defense knocked loose.",
        shape="count",
        polarity="higher",
        source="PLS",
        since=1999,
    ),
    _def_press(
        name="def_safeties",
        label="Def Safeties",
        full_name="Defensive Safeties",
        description="Safeties forced by the defense (two points each).",
        shape="count",
        polarity="higher",
        source="PLS",
        since=1999,
    ),
    _def_to(
        name="def_interceptions",
        label="Def INTs",
        full_name="Defensive Interceptions",
        description="Passes intercepted by the defense.",
        shape="count",
        polarity="higher",
        source="PLS",
        since=1999,
    ),
    # Planned defense expansion (mirrors and defense-only stats).
    _def_total(
        name="first_downs_allowed",
        label="1Ds Allowed",
        full_name="First Downs Allowed",
        description="Total first downs given up by rush, pass, or penalty.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_total(
        name="yards_per_defensive_snap_allowed",
        label="Yds Allowed/Def Snap",
        full_name="Yards Allowed Per Defensive Snap",
        description="Total yards given up divided by defensive snaps.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_total(
        name="epa_per_defensive_snap_allowed",
        label="EPA Allowed/Def Snap",
        full_name="EPA Allowed Per Defensive Snap",
        description="Opponent expected points added per defensive snap.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_total(
        name="success_rate_allowed",
        label="Success % Allowed",
        full_name="Success Rate Allowed",
        description="The share of opponent plays that improved their expected points.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_total(
        name="explosive_play_rate_allowed",
        label="Explosive % Allowed",
        full_name="Explosive Play Rate Allowed",
        description="The share of opponent snaps gaining 20+ pass or 10+ rush yards.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_pass(
        name="attempts_faced",
        label="Att Faced",
        full_name="Pass Attempts Faced",
        description="Official opponent pass attempts against this defense.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="completions_allowed",
        label="Comp Allowed",
        full_name="Completions Allowed",
        description="Opponent passes completed against this defense.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="completion_pct_allowed",
        label="Comp % Allowed",
        full_name="Completion Percentage Allowed",
        description="The share of opponent attempts completed against this defense.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent pass attempts",
        since=1999,
    ),
    _def_pass(
        name="net_passing_yards_allowed",
        label="Net Pass Yds Allowed",
        full_name="Net Passing Yards Allowed",
        description="Passing yards allowed minus opponent sack yardage lost.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pass(
        name="epa_per_dropback_allowed",
        label="EPA/DB Allowed",
        full_name="EPA Per Dropback Allowed",
        description="Opponent passing expected points added per dropback faced.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent dropbacks",
        since=1999,
    ),
    _def_pass(
        name="any_a_allowed",
        label="ANY/A Allowed",
        full_name="Adjusted Net Yards Per Attempt Allowed",
        description=(
            "The best conventional passing stat, from the defense's perspective: what "
            "opposing passers earned per attempt with touchdown, interception, and sack "
            "adjustments."
        ),
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent pass attempts + sacks",
        since=1999,
    ),
    _def_pass(
        name="explosive_pass_rate_allowed",
        label="Expl Pass % Allowed",
        full_name="Explosive Pass Rate Allowed",
        description="Opponent completions of 20+ yards per opponent dropback.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent dropbacks",
        since=1999,
    ),
    _def_pass(
        name="air_yards_allowed",
        label="Air Yds Allowed",
        full_name="Air Yards Allowed",
        description="Total air yards opponents threw for against this defense.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=2006,
    ),
    _def_pass(
        name="yac_allowed",
        label="YAC Allowed",
        full_name="Yards After Catch Allowed",
        description="Yards opponents gained after the catch — a tackling indicator.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pass(
        name="team_passer_rating_allowed",
        label="Rating Allowed",
        full_name="Passer Rating Allowed",
        description="The classic passer rating opposing quarterbacks combined for.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="official NFL formula over opponent attempts",
        since=1999,
    ),
    _def_pass(
        name="deep_attempt_rate_faced",
        label="Deep Att % Faced",
        full_name="Deep Attempt Rate Faced",
        description="How often opponents attacked this defense deep. A context stat.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="opponent pass attempts",
        since=1999,
    ),
    _def_rush(
        name="carries_faced",
        label="Carries Faced",
        full_name="Carries Faced",
        description="Opponent rushing attempts against this defense.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
    ),
    _def_rush(
        name="yards_per_carry_allowed",
        label="Y/C Allowed",
        full_name="Yards Per Carry Allowed",
        description="Opponent rushing yards divided by their carries.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent carries",
        since=1999,
    ),
    _def_rush(
        name="rush_success_rate_allowed",
        label="Rush Success % Allowed",
        full_name="Rushing Success Rate Allowed",
        description="The share of opponent designed runs that improved their expected points.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent designed carries",
        since=1999,
    ),
    _def_rush(
        name="explosive_rush_rate_allowed",
        label="Expl Rush % Allowed",
        full_name="Explosive Rush Rate Allowed",
        description="Opponent runs of 10+ yards per opponent carry.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent carries",
        since=1999,
    ),
    _def_recv(
        name="targets_faced",
        label="Targets Faced",
        full_name="Targets Faced",
        description=(
            "Opponent pass attempts thrown to an intended receiver. Throwaways and spikes are "
            "attempts but not targets."
        ),
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
        note=_TARGETS_GAP_NOTE,
    ),
    _def_recv(
        name="receptions_allowed",
        label="Rec Allowed",
        full_name="Receptions Allowed",
        description="Opponent catches — the same number as completions allowed.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
        duplicate_of="completions_allowed",
    ),
    _def_recv(
        name="receiving_yards_allowed",
        label="Rec Yds Allowed",
        full_name="Receiving Yards Allowed",
        description="Opponent receiving yards — equals passing yards allowed.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
        duplicate_of="passing_yards_allowed",
    ),
    _def_recv(
        name="catch_rate_allowed",
        label="Catch % Allowed",
        full_name="Catch Rate Allowed",
        description="Opponent receptions per target — receiving view of coverage.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent targets",
        since=1999,
        note=_TARGETS_GAP_NOTE,
    ),
    _def_score(
        name="points_per_drive_allowed",
        label="Pts/Drive Allowed",
        full_name="Points Per Drive Allowed",
        description="Points given up per opponent possession.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_score(
        name="red_zone_td_pct_allowed",
        label="RZ TD % Allowed",
        full_name="Red Zone Touchdown Percentage Allowed",
        description="The share of opponent red-zone trips that ended in touchdowns.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent red-zone trips",
        since=1999,
    ),
    _def_score(
        name="goal_to_go_td_pct_allowed",
        label="G2G TD % Allowed",
        full_name="Goal-To-Go Touchdown Percentage Allowed",
        description="Opponent touchdowns per goal-to-go situation faced.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent goal-to-go series",
        since=1999,
    ),
    _def_score(
        name="two_pt_conversion_rate_allowed",
        label="2-Pt % Allowed",
        full_name="Two-Point Conversion Rate Allowed",
        description="Opponent two-point conversion success rate against this defense.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent two-point attempts",
        since=1999,
    ),
    _def_downs(
        name="third_down_pct_allowed",
        label="3rd Down % Allowed",
        full_name="Third Down Percentage Allowed",
        description="Opponent third-down conversion rate against this defense.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent third-down attempts",
        since=1999,
    ),
    _def_downs(
        name="fourth_down_pct_allowed",
        label="4th Down % Allowed",
        full_name="Fourth Down Percentage Allowed",
        description="Opponent fourth-down conversion rate against this defense.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent fourth-down attempts",
        since=1999,
    ),
    _def_downs(
        name="series_conversion_rate_allowed",
        label="Series Conv % Allowed",
        full_name="Series Conversion Rate Allowed",
        description="The share of opponent series that reached a new first down or score.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent series",
        since=1999,
    ),
    _def_downs(
        name="three_and_outs_forced_rate",
        label="3-and-Outs Forced %",
        full_name="Three-and-Outs Forced Rate",
        description="The share of opponent drives forced into three-and-outs.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_drives(
        name="score_pct_per_drive_allowed",
        label="Score %/Drive Allowed",
        full_name="Scoring Rate Per Drive Allowed",
        description="The share of opponent possessions that ended in any score.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_drives(
        name="punts_forced_pct",
        label="Punts Forced %",
        full_name="Punts Forced Rate",
        description="The share of opponent possessions that ended in a punt.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_drives(
        name="avg_starting_field_position_allowed",
        label="Opp Avg Start",
        full_name="Opponent Average Starting Field Position",
        description=(
            "Where opponent drives started on average. Lower (longer fields for them) "
            "is better and reflects special teams and turnover play."
        ),
        shape="avg",
        polarity="lower",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_to(
        name="takeaways",
        label="Takeaways",
        full_name="Takeaways",
        description="Interceptions plus opponent fumbles recovered.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_to(
        name="def_interception_yards",
        label="INT Ret Yds",
        full_name="Interception Return Yards",
        description="Yards gained returning interceptions.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_to(
        name="fumble_recovery_opp",
        label="Opp Fum Rec",
        full_name="Opponent Fumbles Recovered",
        description="Opponent fumbles this defense recovered.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_to(
        name="takeaway_rate_per_defensive_snap",
        label="Takeaway %",
        full_name="Takeaway Rate",
        description="Takeaways divided by defensive snaps.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_to(
        name="takeaways_per_drive",
        label="Takeaways/Drive",
        full_name="Takeaways Per Drive",
        description="Takeaways divided by opponent possessions.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_to(
        name="takeaway_epa",
        label="Takeaway EPA",
        full_name="Takeaway EPA",
        description="Expected points opponents lost on this defense's takeaway plays.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_to(
        name="def_tds",
        label="Def TDs",
        full_name="Defensive Touchdowns",
        description="Touchdowns scored by the defense on returns.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_to(
        name="fumble_recovery_tds",
        label="Fum Ret TDs",
        full_name="Fumble Return Touchdowns",
        description="Touchdowns scored returning recovered fumbles.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_press(
        name="def_sack_yards",
        label="Sack Yds Forced",
        full_name="Sack Yards Forced",
        description="Yards opponents lost to this defense's sacks.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_press(
        name="def_sack_rate_per_dropback",
        label="Sack Rate Forced",
        full_name="Sack Rate Forced",
        description="Sacks divided by opponent dropbacks — pass-rush efficiency.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent dropbacks",
        since=1999,
    ),
    _def_press(
        name="qb_pressure_events_rate",
        label="Pressure Events %",
        full_name="QB Pressure Events Rate",
        description="Sacks plus quarterback hits divided by opponent dropbacks.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent dropbacks",
        since=1999,
    ),
    _def_press(
        name="stuff_rate",
        label="Stuff %",
        full_name="Run Stuff Rate",
        description=(
            "The share of opponent carries other than kneel-downs stopped for no gain or a loss."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent carries other than kneel-downs",
        since=1999,
    ),
    _def_press(
        name="havoc_rate",
        label="Havoc %",
        full_name="Havoc Rate",
        description=(
            "Disruptive plays — tackles for loss, forced fumbles, interceptions, and pass "
            "breakups — divided by defensive snaps."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_press(
        name="defensive_2pt_conversions",
        label="Def 2-Pt",
        full_name="Defensive Two-Point Conversions",
        description="Two-point returns scored by the defense on turnovers during tries.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_pen(
        name="defensive_penalties",
        label="Def Penalties",
        full_name="Defensive Penalties",
        description=(
            "Penalties committed on plays where the opponent had the ball, including the "
            "team's kickoffs, punt returns, and field-goal and extra-point defense."
        ),
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pen(
        name="defensive_penalty_yards",
        label="Def Pen Yds",
        full_name="Defensive Penalty Yards",
        description=(
            "Penalty yards assessed on plays where the opponent had the ball, including the "
            "team's kickoffs, punt returns, and field-goal and extra-point defense."
        ),
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pen(
        name="defensive_pass_interference",
        label="DPI",
        full_name="Defensive Pass Interference Penalties",
        description="Defensive pass interference penalties committed.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pen(
        name="penalty_first_downs_allowed",
        label="Pen 1Ds Gifted",
        full_name="Penalty First Downs Gifted",
        description="Opponent first downs handed over via defensive penalties.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
)

__all__ = [
    "DEFENSE_METRICS",
]
