"""Team offense definitions other than passing and receiving.

Totals, rushing, scoring, downs, drives, turnovers, and penalties.

One part of the team registry that `team_metrics.TEAM_METRICS` assembles in catalog order;
human-readable companion: [docs/stats-catalog.md](../../docs/stats-catalog.md).
"""

from __future__ import annotations

from nfl_sos_ratings.metrics.schema import MetricDef, section

_off_total = section("team", "Offense", "Total")
_off_rush = section("team", "Offense", "Rushing")
_off_score = section("team", "Offense", "Scoring")
_off_downs = section("team", "Offense", "Downs & Conversions")
_off_drives = section("team", "Offense", "Drives & Field Position")
_off_to = section("team", "Offense", "Turnovers")
_off_pen = section("team", "Offense", "Penalties")

OFFENSE_TOTAL_METRICS: tuple[MetricDef, ...] = (
    _off_total(
        name="offensive_snaps",
        label="Off Snaps",
        full_name="Offensive Snaps",
        description=(
            "Scrimmage plays run by the offense: dropbacks, rushes, kneels, and spikes. The "
            "denominator for per-offensive-snap rates."
        ),
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_total(
        name="total_yards",
        label="Total Yds",
        full_name="Total Yards",
        description="Passing yards plus rushing yards gained by the offense.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
        note="Sums passing_yards and rushing_yards.",
    ),
    _off_total(
        name="yards_per_offensive_snap",
        label="Yds/Off Snap",
        full_name="Yards Per Offensive Snap",
        description="Total yards divided by offensive snaps — overall offensive efficiency.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="first_downs",
        label="First Downs",
        full_name="First Downs",
        description="First downs gained by rush, pass, or opponent penalty.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_total(
        name="scrimmage_tds",
        label="Scrimmage TDs",
        full_name="Scrimmage Touchdowns",
        description="Touchdowns scored by the offense: passing plus rushing touchdowns.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_total(
        name="offensive_epa",
        label="Off EPA",
        full_name="Offensive EPA",
        description=(
            "Total expected points added on offensive plays. EPA measures how much each "
            "play changed the team's expected score, so it credits down, distance, and "
            "field position — not just raw yards."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_total(
        name="epa_per_offensive_snap",
        label="EPA/Off Snap",
        full_name="EPA Per Offensive Snap",
        description="Offensive expected points added per snap — the core efficiency stat.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="success_rate",
        label="Success %",
        full_name="Offensive Success Rate",
        description=(
            "The share of offensive plays that improved the team's expected points. A "
            "consistency measure that ignores how big each gain was."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
        percent=True,
    ),
    _off_total(
        name="explosive_play_rate",
        label="Explosive %",
        full_name="Explosive Play Rate",
        description=(
            "The share of snaps gaining 20+ passing yards or 10+ rushing yards — the "
            "big-play component of offense."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
        percent=True,
    ),
    _off_total(
        name="no_huddle_rate",
        label="No-Huddle %",
        full_name="No-Huddle Rate",
        description="The share of offensive snaps run without a huddle. A style stat.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
        percent=True,
    ),
    _off_total(
        name="shotgun_rate",
        label="Shotgun %",
        full_name="Shotgun Rate",
        description="The share of offensive snaps taken from the shotgun. A style stat.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
        percent=True,
    ),
    _off_total(
        name="pass_rate",
        label="Pass %",
        full_name="Pass Rate",
        description="Dropbacks divided by scrimmage snaps — how pass-heavy the offense is.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
        percent=True,
    ),
    _off_total(
        name="early_down_pass_rate",
        label="Early-Down Pass %",
        full_name="Early-Down Pass Rate",
        description=(
            "Dropbacks on first and second down divided by early-down snaps. Passing early "
            "is the analytics-favored tendency signal."
        ),
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="early-down snaps",
        since=1999,
        percent=True,
    ),
    _off_total(
        name="pass_rate_over_expected",
        label="PROE",
        full_name="Pass Rate Over Expected",
        description=(
            "How much more (or less) often the team passes than the game situations would "
            "predict. Positive means more pass-heavy than expected."
        ),
        shape="avg",
        polarity="neutral",
        source="PBP",
        denominator="offensive snaps (model-expected pass rate)",
        since=2006,
    ),
    _off_total(
        name="offensive_wpa",
        label="Off WPA",
        full_name="Offensive Win Probability Added",
        description=(
            "How much the offense's plays moved the team's chance of winning, summed over "
            "the season. Weighted toward high-leverage moments."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
)

OFFENSE_RUSHING_METRICS: tuple[MetricDef, ...] = (
    _off_rush(
        name="rushing_yards",
        label="Rush Yds",
        full_name="Rushing Yards",
        description="Yards gained on the ground, including quarterback runs.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="rushing_epa",
        label="Rush EPA",
        full_name="Rushing EPA",
        description=(
            "Expected points added on rushing plays. Rushing EPA is usually negative "
            "league-wide, so closer to zero (or positive) is good."
        ),
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="rushing_tds",
        label="Rush TDs",
        full_name="Rushing Touchdowns",
        description="Touchdowns scored on the ground.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="rushing_first_downs",
        label="Rush 1Ds",
        full_name="Rushing First Downs",
        description="First downs gained on the ground.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="rushing_fumbles_lost",
        label="Rush Fum Lost",
        full_name="Rushing Fumbles Lost",
        description="Fumbles lost to the defense on rushing plays.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="carries",
        label="Carries",
        full_name="Carries",
        description="Official rushing attempts, including scrambles and kneel-downs.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="designed_carries",
        label="Designed Carries",
        full_name="Designed Carries",
        description="Rushing attempts excluding scrambles and kneel-downs — called runs.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_rush(
        name="yards_per_carry",
        label="Y/C",
        full_name="Yards Per Carry",
        description="Rushing yards divided by carries.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="carries",
        since=1999,
    ),
    _off_rush(
        name="epa_per_carry",
        label="EPA/Carry",
        full_name="EPA Per Carry",
        description="Rushing expected points added per carry — rushing efficiency.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="carries",
        since=1999,
    ),
    _off_rush(
        name="rush_success_rate",
        label="Rush Success %",
        full_name="Rushing Success Rate",
        description="The share of designed runs that improved the team's expected points.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="designed carries",
        since=1999,
        percent=True,
    ),
    _off_rush(
        name="explosive_rush_rate",
        label="Explosive Rush %",
        full_name="Explosive Rush Rate",
        description="Runs of 10+ yards divided by carries.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="carries",
        since=1999,
        percent=True,
    ),
    _off_rush(
        name="stuffed_run_rate",
        label="Stuffed %",
        full_name="Stuffed Run Rate",
        description=("The share of carries other than kneel-downs stopped for no gain or a loss."),
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="carries other than kneel-downs",
        since=1999,
        percent=True,
    ),
    _off_rush(
        name="rushing_fumbles",
        label="Rush Fumbles",
        full_name="Rushing Fumbles",
        description="Fumbles on rushing plays, whether or not the team lost the ball.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="longest_rush",
        label="Long Rush",
        full_name="Longest Rush",
        description="The team's longest run of the season, in yards.",
        shape="max",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_rush(
        name="rushing_2pt_conversions",
        label="2-Pt Rushes",
        full_name="Two-Point Conversion Rushes",
        description="Successful two-point conversions run in.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
)

OFFENSE_SCORING_METRICS: tuple[MetricDef, ...] = (
    _off_score(
        name="total_tds",
        label="Total TDs",
        full_name="Total Touchdowns",
        description="All touchdowns scored: offense, defense, and special teams.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_score(
        name="offensive_tds",
        label="Off TDs",
        full_name="Offensive Touchdowns",
        description="Passing plus rushing touchdowns.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
        duplicate_of="scrimmage_tds",
    ),
    _off_score(
        name="points_per_drive",
        label="Pts/Drive",
        full_name="Points Per Drive",
        description="Offensive points divided by offensive possessions.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_score(
        name="red_zone_trips",
        label="RZ Trips",
        full_name="Red Zone Trips",
        description="Drives that reached the opponent's 20-yard line.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_score(
        name="red_zone_td_pct",
        label="RZ TD %",
        full_name="Red Zone Touchdown Percentage",
        description="The share of red-zone trips that ended in a touchdown.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="red-zone trips",
        since=1999,
        percent=True,
    ),
    _off_score(
        name="points_per_red_zone_trip",
        label="Pts/RZ Trip",
        full_name="Points Per Red Zone Trip",
        description="Points scored on red-zone drives divided by red-zone trips.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="red-zone trips",
        since=1999,
    ),
    _off_score(
        name="goal_to_go_td_pct",
        label="G2G TD %",
        full_name="Goal-To-Go Touchdown Percentage",
        description="Touchdowns divided by goal-to-go situations.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="goal-to-go series",
        since=1999,
        percent=True,
    ),
    _off_score(
        name="two_pt_attempts",
        label="2-Pt Att",
        full_name="Two-Point Attempts",
        description="Two-point conversion tries.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
    ),
    _off_score(
        name="two_pt_conversions",
        label="2-Pt Made",
        full_name="Two-Point Conversions",
        description="Successful two-point conversions.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_score(
        name="two_pt_conversion_rate",
        label="2-Pt %",
        full_name="Two-Point Conversion Rate",
        description="Successful two-point tries divided by attempts.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="two-point attempts",
        since=1999,
        percent=True,
    ),
)

OFFENSE_DOWNS_METRICS: tuple[MetricDef, ...] = (
    _off_downs(
        name="first_downs_penalty",
        label="Penalty 1Ds",
        full_name="First Downs by Penalty",
        description="First downs awarded via defensive penalties.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="third_down_attempts",
        label="3rd Down Att",
        full_name="Third Down Attempts",
        description="Third downs faced by the offense.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="third_down_conversions",
        label="3rd Down Conv",
        full_name="Third Down Conversions",
        description="Third downs converted into a first down or touchdown.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="third_down_pct",
        label="3rd Down %",
        full_name="Third Down Conversion Percentage",
        description="Third downs converted divided by third downs faced.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="third-down attempts",
        since=1999,
        percent=True,
    ),
    _off_downs(
        name="third_down_avg_distance",
        label="3rd Down Dist",
        full_name="Average Third Down Distance",
        description=(
            "Average yards to go on third down. Shorter means the offense stays on "
            "schedule on early downs."
        ),
        shape="avg",
        polarity="lower",
        source="PBP",
        denominator="third downs faced",
        since=1999,
    ),
    _off_downs(
        name="fourth_down_attempts",
        label="4th Down Att",
        full_name="Fourth Down Attempts",
        description="Fourth downs the offense went for.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="fourth_down_conversions",
        label="4th Down Conv",
        full_name="Fourth Down Conversions",
        description="Fourth-down tries converted.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="fourth_down_pct",
        label="4th Down %",
        full_name="Fourth Down Conversion Percentage",
        description="Fourth-down tries converted divided by tries.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="fourth-down attempts",
        since=1999,
        percent=True,
    ),
    _off_downs(
        name="fourth_down_go_rate",
        label="4th Down Go %",
        full_name="Fourth Down Go Rate",
        description=(
            "How often the team went for it on fourth down instead of kicking. An "
            "aggressiveness style stat."
        ),
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="fourth downs faced",
        since=1999,
        percent=True,
    ),
    _off_downs(
        name="fourth_down_aggressiveness",
        label="4th Down Aggr",
        full_name="Fourth Down Aggressiveness",
        description=(
            "Go-for-it rate on fourth-and-short (2 yards or less), where analytics usually "
            "favors going for it."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="fourth-and-short situations",
        since=1999,
        percent=True,
    ),
    _off_downs(
        name="series",
        label="Series",
        full_name="Offensive Series",
        description="First-down series the offense ran (each new set of downs).",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="series_conversion_rate",
        label="Series Conv %",
        full_name="Series Conversion Rate",
        description=(
            "The share of first-down series that gained another first down or scored — a "
            "steadier version of third-down percentage."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="series",
        since=1999,
        percent=True,
    ),
    _off_downs(
        name="three_and_out_rate",
        label="3-and-Out %",
        full_name="Three-and-Out Rate",
        description="The share of drives that went three plays and punted.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="drives",
        since=1999,
        percent=True,
    ),
    _off_downs(
        name="turnovers_on_downs",
        label="TO on Downs",
        full_name="Turnovers on Downs",
        description="Failed fourth-down tries that handed the ball over.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
)

OFFENSE_DRIVES_METRICS: tuple[MetricDef, ...] = (
    _off_drives(
        name="drives",
        label="Drives",
        full_name="Offensive Drives",
        description="Offensive possessions. The denominator for per-drive rates.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_drives(
        name="yards_per_drive",
        label="Yds/Drive",
        full_name="Yards Per Drive",
        description="Net yards gained per offensive possession.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="plays_per_drive",
        label="Plays/Drive",
        full_name="Plays Per Drive",
        description="Average number of plays run per possession.",
        shape="avg",
        polarity="neutral",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="time_per_drive",
        label="Time/Drive",
        full_name="Time Per Drive",
        description="Average clock time used per possession.",
        shape="avg",
        polarity="neutral",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="first_downs_per_drive",
        label="1Ds/Drive",
        full_name="First Downs Per Drive",
        description="Average first downs gained per possession.",
        shape="avg",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="score_pct_per_drive",
        label="Score %/Drive",
        full_name="Scoring Rate Per Drive",
        description="The share of possessions ending in any score.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
        percent=True,
    ),
    _off_drives(
        name="punt_pct_per_drive",
        label="Punt %/Drive",
        full_name="Punt Rate Per Drive",
        description="The share of possessions ending in a punt.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="drives",
        since=1999,
        percent=True,
    ),
    _off_drives(
        name="turnover_pct_per_drive",
        label="TO %/Drive",
        full_name="Turnover Rate Per Drive",
        description="The share of possessions ending in a giveaway.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="drives",
        since=1999,
        percent=True,
    ),
    _off_drives(
        name="avg_starting_field_position",
        label="Avg Start",
        full_name="Average Starting Field Position",
        description=(
            "Where drives started on average, in yards from the team's own goal line. "
            "Higher means shorter fields to score."
        ),
        shape="avg",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="long_field_score_pct",
        label="Long-Field Score %",
        full_name="Long-Field Scoring Rate",
        description="Scoring rate on drives that started inside the team's own 25.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="long-field drives",
        since=1999,
        percent=True,
    ),
    _off_drives(
        name="drive_penalty_yards",
        label="Drive Pen Yds",
        full_name="Drive Penalty Yards",
        description=(
            "Net penalty yards on the team's drives: yards the defense's fouls gave the offense "
            "minus yards its own fouls cost it."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
)

OFFENSE_TURNOVER_METRICS: tuple[MetricDef, ...] = (
    _off_to(
        name="giveaways",
        label="Giveaways",
        full_name="Giveaways",
        description="Interceptions thrown plus fumbles lost.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _off_to(
        name="fumbles",
        label="Fumbles",
        full_name="Fumbles",
        description="All offensive fumbles, whether recovered or lost.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_to(
        name="fumbles_lost",
        label="Fumbles Lost",
        full_name="Fumbles Lost",
        description="Offensive fumbles the defense recovered.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_to(
        name="giveaway_rate_per_offensive_snap",
        label="Giveaway %",
        full_name="Giveaway Rate",
        description="Giveaways divided by offensive snaps.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
        percent=True,
    ),
    _off_to(
        name="giveaways_per_drive",
        label="Giveaways/Drive",
        full_name="Giveaways Per Drive",
        description="Giveaways divided by possessions.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_to(
        name="turnover_epa",
        label="TO EPA",
        full_name="Turnover EPA",
        description=(
            "Expected points lost on giveaway plays — how costly the turnovers were, not "
            "just how many there were."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
        note="Values are negative; closer to zero means cheaper turnovers.",
    ),
)

OFFENSE_PENALTY_METRICS: tuple[MetricDef, ...] = (
    _off_pen(
        name="penalties",
        label="Penalties",
        full_name="Penalties",
        description="Penalties committed by the team across all units.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_pen(
        name="penalty_yards",
        label="Penalty Yds",
        full_name="Penalty Yards",
        description="Yards assessed against the team on its penalties.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_pen(
        name="offensive_penalties",
        label="Off Penalties",
        full_name="Offensive Penalties",
        description=(
            "Penalties committed on plays where the team had the ball, including its punts, "
            "field goals, extra points, and kickoff returns."
        ),
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _off_pen(
        name="offensive_penalty_yards",
        label="Off Pen Yds",
        full_name="Offensive Penalty Yards",
        description=(
            "Penalty yards assessed on plays where the team had the ball, including its punts, "
            "field goals, extra points, and kickoff returns."
        ),
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _off_pen(
        name="presnap_penalty_rate",
        label="Pre-Snap Pen %",
        full_name="Pre-Snap Penalty Rate",
        description=(
            "False starts, delays of game, and similar self-inflicted penalties per "
            "offensive snap. A discipline measure."
        ),
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
        percent=True,
    ),
    _off_pen(
        name="penalty_rate_per_offensive_snap",
        label="Off Pen %",
        full_name="Offensive Penalty Rate",
        description=(
            "Offensive penalties (special-teams plays with the ball included) divided by "
            "offensive snaps."
        ),
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
        percent=True,
    ),
)

__all__ = [
    "OFFENSE_DOWNS_METRICS",
    "OFFENSE_DRIVES_METRICS",
    "OFFENSE_PENALTY_METRICS",
    "OFFENSE_RUSHING_METRICS",
    "OFFENSE_SCORING_METRICS",
    "OFFENSE_TOTAL_METRICS",
    "OFFENSE_TURNOVER_METRICS",
]
