"""Team metric definitions: every team column the pipeline publishes.

Human-readable companion: [docs/stats-catalog.md](../../docs/stats-catalog.md).
"""

from __future__ import annotations

from nfl_sos_ratings.metrics.schema import MetricDef, section

_ratings = section("team", "Schedule-Adjusted Ratings")
_overall = section("team", "Overall")
_off_total = section("team", "Offense", "Total")
_off_pass = section("team", "Offense", "Passing")
_off_rush = section("team", "Offense", "Rushing")
_off_recv = section("team", "Offense", "Receiving")
_off_score = section("team", "Offense", "Scoring")
_off_downs = section("team", "Offense", "Downs & Conversions")
_off_drives = section("team", "Offense", "Drives & Field Position")
_off_to = section("team", "Offense", "Turnovers")
_off_pen = section("team", "Offense", "Penalties")
_def_total = section("team", "Defense", "Total")
_def_pass = section("team", "Defense", "Passing")
_def_rush = section("team", "Defense", "Rushing")
_def_recv = section("team", "Defense", "Receiving")
_def_score = section("team", "Defense", "Scoring")
_def_downs = section("team", "Defense", "Downs & Conversions")
_def_drives = section("team", "Defense", "Drives & Field Position")
_def_to = section("team", "Defense", "Turnovers")
_def_press = section("team", "Defense", "Pressure & Playmaking")
_def_pen = section("team", "Defense", "Penalties")
_special_teams = section("team", "Special Teams")

RATING_METRICS: tuple[MetricDef, ...] = (
    _ratings(
        name="team_rating",
        label="Team Rating",
        full_name="Team Rating",
        description=(
            "How many points per game better than an average team this team was on a neutral "
            "field, after adjusting for every opponent it faced. It is the sum of the offense, "
            "defense, and special-teams ratings, all built from expected points added (EPA). "
            "0 is an average team."
        ),
        shape="score",
        polarity="higher",
        source="D",
        since=1999,
    ),
    _ratings(
        name="offense_rating",
        label="Off Rating",
        full_name="Offense Rating",
        description=(
            "Points per game the offense produced above an average offense, measured by "
            "scrimmage EPA per play and adjusted for the defenses it faced."
        ),
        shape="score",
        polarity="higher",
        source="D",
        since=1999,
    ),
    _ratings(
        name="defense_rating",
        label="Def Rating",
        full_name="Defense Rating",
        description=(
            "Points per game the defense prevented compared with an average defense, measured "
            "by scrimmage EPA per play allowed and adjusted for the offenses it faced. Higher "
            "is better."
        ),
        shape="score",
        polarity="higher",
        source="D",
        since=1999,
    ),
    _ratings(
        name="special_teams_rating",
        label="ST Rating",
        full_name="Special Teams Rating",
        description=(
            "Points per game gained on special-teams plays (kicks, punts, returns, field goals, "
            "and extra points) compared with an average team, adjusted for the opponents faced."
        ),
        shape="score",
        polarity="higher",
        source="D",
        since=1999,
    ),
    _ratings(
        name="SRS",
        label="SRS",
        full_name="Simple Rating System",
        description=(
            "A classic point-margin rating solved across the whole league at once. Positive "
            "means the team outscored opponents by more than an average team would have "
            "against the same schedule, measured in points per game."
        ),
        shape="score",
        polarity="higher",
        source="D",
        since=1999,
    ),
    _ratings(
        name="sos",
        label="SoS",
        full_name="Strength of Schedule",
        description=(
            "The average Team Rating of the opponents this team played, one entry per game, in "
            "points per game. Each opponent is rated without its games against this team, so "
            "beating an opponent badly cannot make that opponent look weaker here. Positive "
            "means a harder-than-average schedule. Early in a season, opponents that have played "
            "no one else yet are left out. Context, not a team grade."
        ),
        shape="score",
        polarity="higher",
        source="D",
        since=1999,
        contextual=True,
    ),
)

OVERALL_METRICS: tuple[MetricDef, ...] = (
    _overall(
        name="team",
        label="Team",
        full_name="Team",
        description="The team's standard NFL abbreviation, such as KC or PHI.",
        shape="id",
        polarity="neutral",
        source="SCH",
    ),
    _overall(
        name="game_id",
        label="Game ID",
        full_name="Game ID",
        description="The unique nflverse identifier for one game, useful for deep links.",
        shape="id",
        polarity="neutral",
        source="SCH",
    ),
    _overall(
        name="week",
        label="Week",
        full_name="Week",
        description=(
            "The regular-season week: on a game row, the week the game was played; on a "
            "rating-history row, the last week of games the rating includes."
        ),
        shape="id",
        polarity="neutral",
        source="SCH",
    ),
    _overall(
        name="opponent_team",
        label="Opponent",
        full_name="Opponent Team",
        description="The opposing team in this game or in the summarized opponent row.",
        shape="id",
        polarity="neutral",
        source="SCH",
    ),
    _overall(
        name="is_home",
        label="Home",
        full_name="Home Team Flag",
        description="Whether this team was the home side in the game represented by the row.",
        shape="flag",
        polarity="neutral",
        source="SCH",
        since=1999,
    ),
    _overall(
        name="games_played",
        label="Games",
        full_name="Games Played",
        description="Regular-season games played. Rate stats divide by this number.",
        shape="count",
        polarity="neutral",
        source="SCH",
        since=1999,
    ),
    _overall(
        name="games",
        label="Games",
        full_name="Games",
        description="The number of games represented by this row of the table.",
        shape="count",
        polarity="neutral",
        source="SCH",
        since=1999,
    ),
    _overall(
        name="wins",
        label="Wins",
        full_name="Wins",
        description="Regular-season games won. Treated as an outcome, not a rating input.",
        shape="count",
        polarity="higher",
        source="SCH",
        since=1999,
    ),
    _overall(
        name="losses",
        label="Losses",
        full_name="Losses",
        description="Regular-season games lost. Treated as an outcome, not a rating input.",
        shape="count",
        polarity="lower",
        source="SCH",
        since=1999,
    ),
    _overall(
        name="ties",
        label="Ties",
        full_name="Ties",
        description="Regular-season games that ended tied after overtime.",
        shape="count",
        polarity="neutral",
        source="SCH",
        since=1999,
    ),
    _overall(
        name="win_pct",
        label="Win %",
        full_name="Win Percentage",
        description=(
            "Share of games won, counting a tie as half a win: (wins + 0.5 x ties) divided "
            "by games played."
        ),
        shape="rate",
        polarity="higher",
        source="D",
        denominator="games played",
        since=1999,
        formula="(wins + 0.5 * ties) / games_played",
    ),
    _overall(
        name="win_value",
        label="Win Value",
        full_name="Win Value",
        description=(
            "The game result as a number: 1 for a win, 0.5 for a tie, 0 for a loss. In "
            "summary rows it is the average across the games included."
        ),
        shape="avg",
        polarity="higher",
        source="D",
        denominator="games included",
        since=1999,
    ),
    _overall(
        name="points_for",
        label="Points For",
        full_name="Points Scored",
        description="Total points the team scored, including all offense, defense, and kicks.",
        shape="count",
        polarity="higher",
        source="SCH",
        since=1999,
    ),
    _overall(
        name="points_allowed",
        label="Points Allowed",
        full_name="Points Allowed",
        description="Total points the team gave up. Fewer points allowed is better.",
        shape="count",
        polarity="lower",
        source="SCH",
        since=1999,
    ),
    _overall(
        name="point_margin",
        label="Point Margin",
        full_name="Point Margin",
        description=(
            "Points scored minus points allowed. A restatement of the two point totals, "
            "kept for display because it is the most intuitive whole-team summary."
        ),
        shape="count",
        polarity="higher",
        source="D",
        since=1999,
        formula="points_for - points_allowed",
        note="Restates points_for and points_allowed.",
    ),
    _overall(
        name="turnover_margin",
        label="TO Margin",
        full_name="Turnover Margin",
        description=(
            "Takeaways minus giveaways. Positive means the team won the turnover battle "
            "across the season."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _overall(
        name="points_per_offensive_snap",
        label="Points/Off Snap",
        full_name="Points Per Offensive Snap",
        description=(
            "Points scored divided by offensive snaps — scoring efficiency that does not "
            "reward teams simply for running more plays."
        ),
        shape="rate",
        polarity="higher",
        source="D",
        denominator="offensive snaps",
        since=1999,
    ),
    _overall(
        name="points_allowed_per_defensive_snap",
        label="Points Allowed/Def Snap",
        full_name="Points Allowed Per Defensive Snap",
        description=(
            "Points given up divided by defensive snaps — defensive scoring efficiency that "
            "does not punish defenses simply for facing more plays."
        ),
        shape="rate",
        polarity="lower",
        source="D",
        denominator="defensive snaps",
        since=1999,
    ),
    _overall(
        name="total_yards_differential",
        label="Total Yds Diff",
        full_name="Total Yards Differential",
        description="Yards gained minus yards allowed across the season.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _overall(
        name="penalty_differential",
        label="Penalty Diff",
        full_name="Penalty Differential",
        description="Opponent penalties minus the team's own penalties; positive is good.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _overall(
        name="penalty_yards_differential",
        label="Pen Yds Diff",
        full_name="Penalty Yards Differential",
        description="Opponent penalty yards minus the team's own penalty yards.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _overall(
        name="epa_margin_per_play",
        label="EPA Margin/Play",
        full_name="EPA Margin Per Play",
        description=(
            "Offensive expected points added per play minus defensive EPA allowed per play "
            "— the single best play-level summary of team strength."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="scrimmage snaps",
        since=1999,
    ),
    _overall(
        name="success_rate_margin",
        label="Success Margin",
        full_name="Success Rate Margin",
        description=(
            "Offensive success rate minus defensive success rate allowed. Success means a "
            "play that improved the team's expected points."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="scrimmage snaps",
        since=1999,
    ),
)

OFFENSE_TOTAL_METRICS: tuple[MetricDef, ...] = (
    _off_total(
        name="offensive_snaps",
        label="Off Snaps",
        full_name="Offensive Snaps",
        description=(
            "Scrimmage plays run by the offense: dropbacks, rushes, kneels, and spikes. The "
            "denominator for per-offensive-snap rates."
        ),
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_total(
        name="total_yards",
        label="Total Yds",
        full_name="Total Yards",
        description="Passing yards plus rushing yards gained by the offense.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
        note="Sums passing_yards and rushing_yards.",
    ),
    _off_total(
        name="yards_per_offensive_snap",
        label="Yds/Off Snap",
        full_name="Yards Per Offensive Snap",
        description="Total yards divided by offensive snaps — overall offensive efficiency.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="first_downs",
        label="First Downs",
        full_name="First Downs",
        description="First downs gained by rush, pass, or opponent penalty.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_total(
        name="scrimmage_tds",
        label="Scrimmage TDs",
        full_name="Scrimmage Touchdowns",
        description="Touchdowns scored by the offense: passing plus rushing touchdowns.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_total(
        name="offensive_epa",
        label="Off EPA",
        full_name="Offensive EPA",
        description=(
            "Total expected points added on offensive plays. EPA measures how much each "
            "play changed the team's expected score, so it credits down, distance, and "
            "field position — not just raw yards."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_total(
        name="epa_per_offensive_snap",
        label="EPA/Off Snap",
        full_name="EPA Per Offensive Snap",
        description="Offensive expected points added per snap — the core efficiency stat.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="success_rate",
        label="Success %",
        full_name="Offensive Success Rate",
        description=(
            "The share of offensive plays that improved the team's expected points. A "
            "consistency measure that ignores how big each gain was."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="explosive_play_rate",
        label="Explosive %",
        full_name="Explosive Play Rate",
        description=(
            "The share of snaps gaining 20+ passing yards or 10+ rushing yards — the "
            "big-play component of offense."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="no_huddle_rate",
        label="No-Huddle %",
        full_name="No-Huddle Rate",
        description="The share of offensive snaps run without a huddle. A style stat.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="shotgun_rate",
        label="Shotgun %",
        full_name="Shotgun Rate",
        description="The share of offensive snaps taken from the shotgun. A style stat.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="pass_rate",
        label="Pass %",
        full_name="Pass Rate",
        description="Dropbacks divided by scrimmage snaps — how pass-heavy the offense is.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_total(
        name="early_down_pass_rate",
        label="Early-Down Pass %",
        full_name="Early-Down Pass Rate",
        description=(
            "Dropbacks on first and second down divided by early-down snaps. Passing early "
            "is the analytics-favored tendency signal."
        ),
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="early-down snaps",
        since=1999,
    ),
    _off_total(
        name="pass_rate_over_expected",
        label="PROE",
        full_name="Pass Rate Over Expected",
        description=(
            "How much more (or less) often the team passes than the game situations would "
            "predict. Positive means more pass-heavy than expected."
        ),
        shape="avg",
        polarity="neutral",
        source="PBP",
        denominator="offensive snaps (model-expected pass rate)",
        since=2006,
    ),
    _off_total(
        name="offensive_wpa",
        label="Off WPA",
        full_name="Offensive Win Probability Added",
        description=(
            "How much the offense's plays moved the team's chance of winning, summed over "
            "the season. Weighted toward high-leverage moments."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
)

OFFENSE_PASSING_METRICS: tuple[MetricDef, ...] = (
    _off_pass(
        name="passing_yards",
        label="Pass Yds",
        full_name="Passing Yards",
        description=(
            "Gross passing yards on completions. Sack yardage is not subtracted here — see "
            "net passing yards for the NFL.com team convention."
        ),
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="passing_epa",
        label="Pass EPA",
        full_name="Passing EPA",
        description=(
            "Expected points added on dropbacks. Positive means the passing game moved the "
            "team toward scoring more than an average offense would have."
        ),
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="passing_tds",
        label="Pass TDs",
        full_name="Passing Touchdowns",
        description="Touchdown passes thrown by the team.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="passing_first_downs",
        label="Pass 1Ds",
        full_name="Passing First Downs",
        description="First downs gained through the air.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="passing_cpoe",
        label="Pass CPOE",
        full_name="Completion Percentage Above Expectation",
        description=(
            "How much higher the team's completion rate was than the difficulty of its "
            "throws would predict, in percentage points. Positive means more accurate than "
            "expected."
        ),
        shape="avg",
        polarity="higher",
        source="PBP +TS",
        denominator="pass attempts (model-expected completions)",
        since=2006,
    ),
    _off_pass(
        name="sacks_suffered",
        label="Sacks Taken",
        full_name="Sacks Suffered",
        description="Times the team's quarterbacks were sacked. Fewer is better.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="passing_interceptions",
        label="INTs Thrown",
        full_name="Interceptions Thrown",
        description="Passes intercepted by the defense. Fewer is better.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="sack_fumbles_lost",
        label="Sack Fum Lost",
        full_name="Sack Fumbles Lost",
        description="Fumbles lost to the defense on sack plays (strip-sacks).",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="attempts",
        label="Att",
        full_name="Pass Attempts",
        description=(
            "Official pass attempts. Excludes sacks and two-point conversion tries, "
            "matching the league's official counting."
        ),
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
        formula="pass_attempt - sack, excluding two_point_attempt",
    ),
    _off_pass(
        name="completions",
        label="Comp",
        full_name="Completions",
        description="Completed passes by the team.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="completion_pct",
        label="Comp %",
        full_name="Completion Percentage",
        description="The share of official pass attempts that were completed.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="pass attempts",
        since=1999,
    ),
    _off_pass(
        name="net_passing_yards",
        label="Net Pass Yds",
        full_name="Net Passing Yards",
        description=(
            "Passing yards minus yards lost to sacks — the NFL.com team convention for "
            "passing offense."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
        formula="passing_yards - sack_yards_lost (positive magnitude)",
    ),
    _off_pass(
        name="dropbacks",
        label="Dropbacks",
        full_name="Dropbacks",
        description=(
            "Pass attempts plus sacks plus scrambles — every play that started as a pass. "
            "The natural denominator for passing efficiency."
        ),
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_pass(
        name="sack_yards_lost",
        label="Sack Yds Lost",
        full_name="Sack Yards Lost",
        description="Yards lost on sacks, shown as a positive number. Fewer is better.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
        note="team_stats stores this negative upstream; the ETL normalizes the sign.",
    ),
    _off_pass(
        name="sack_rate_per_dropback",
        label="Sack Rate",
        full_name="Sack Rate",
        description="The share of dropbacks that ended in a sack. Lower is better.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="dropbacks",
        since=1999,
    ),
    _off_pass(
        name="scrambles",
        label="Scrambles",
        full_name="QB Scrambles",
        description="Dropbacks on which the quarterback took off and ran.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_pass(
        name="scramble_yards",
        label="Scramble Yds",
        full_name="Scramble Yards",
        description="Rushing yards gained on quarterback scrambles.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_pass(
        name="passing_air_yards",
        label="Air Yds",
        full_name="Passing Air Yards",
        description=(
            "Total distance the ball traveled past the line of scrimmage on all throws, "
            "including incompletions — a measure of how far downfield the team attacks."
        ),
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=2006,
    ),
    _off_pass(
        name="passing_yards_after_catch",
        label="YAC",
        full_name="Passing Yards After Catch",
        description="Yards receivers gained after catching the ball.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="air_yards_per_attempt",
        label="aDOT",
        full_name="Air Yards Per Attempt (aDOT)",
        description=(
            "Average depth of target: how far downfield the average throw traveled. A "
            "style stat, not a quality grade."
        ),
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="pass attempts",
        since=2006,
    ),
    _off_pass(
        name="yac_per_completion",
        label="YAC/Comp",
        full_name="Yards After Catch Per Completion",
        description="Average yards gained after the catch on completed passes.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="completions",
        since=1999,
    ),
    _off_pass(
        name="yards_per_attempt",
        label="Y/A",
        full_name="Yards Per Attempt",
        description="Passing yards divided by official pass attempts.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="pass attempts",
        since=1999,
    ),
    _off_pass(
        name="net_yards_per_attempt",
        label="NY/A",
        full_name="Net Yards Per Attempt",
        description=(
            "Passing yards minus sack yards, divided by attempts plus sacks — yards per "
            "dropback-style efficiency that charges the offense for sacks."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="pass attempts + sacks",
        since=1999,
        formula="(passing_yards - sack_yards_lost) / (attempts + sacks)",
    ),
    _off_pass(
        name="adjusted_net_yards_per_attempt",
        label="ANY/A",
        full_name="Adjusted Net Yards Per Attempt",
        description=(
            "The best single conventional passing stat: yards per attempt with a +20-yard "
            "bonus per touchdown, a -45-yard penalty per interception, and sacks counted "
            "against."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="pass attempts + sacks",
        since=1999,
        formula="(yards + 20*TD - 45*INT - sack_yards) / (attempts + sacks)",
    ),
    _off_pass(
        name="yards_per_dropback",
        label="Yds/DB",
        full_name="Yards Per Dropback",
        description="Passing yards divided by dropbacks, so sacks and scrambles count.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="dropbacks",
        since=1999,
    ),
    _off_pass(
        name="epa_per_dropback",
        label="EPA/DB",
        full_name="EPA Per Dropback",
        description="Passing expected points added per dropback — passing efficiency.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="dropbacks",
        since=1999,
    ),
    _off_pass(
        name="pass_success_rate",
        label="Pass Success %",
        full_name="Passing Success Rate",
        description="The share of dropbacks that improved the team's expected points.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="dropbacks",
        since=1999,
    ),
    _off_pass(
        name="team_passer_rating",
        label="Passer Rating",
        full_name="Team Passer Rating",
        description=(
            "The classic NFL passer-rating formula (0 to 158.3) computed on the team's "
            "combined passing totals."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="official NFL formula over attempts",
        since=1999,
    ),
    _off_pass(
        name="passing_td_rate_per_attempt",
        label="TD %",
        full_name="Passing Touchdown Rate",
        description="The share of pass attempts that scored touchdowns.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="pass attempts",
        since=1999,
    ),
    _off_pass(
        name="int_rate_per_attempt",
        label="INT %",
        full_name="Interception Rate",
        description="The share of pass attempts that were intercepted. Lower is better.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="pass attempts",
        since=1999,
    ),
    _off_pass(
        name="explosive_pass_rate",
        label="Explosive Pass %",
        full_name="Explosive Pass Rate",
        description="Completions of 20+ yards divided by dropbacks.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="dropbacks",
        since=1999,
    ),
    _off_pass(
        name="deep_attempt_rate",
        label="Deep Att %",
        full_name="Deep Attempt Rate",
        description="The share of attempts thrown deep (16+ air yards). A style stat.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="pass attempts",
        since=1999,
    ),
    _off_pass(
        name="longest_pass",
        label="Long Pass",
        full_name="Longest Completed Pass",
        description="The team's longest completed pass of the season, in yards.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_pass(
        name="sack_fumbles",
        label="Sack Fumbles",
        full_name="Sack Fumbles",
        description="Fumbles on sack plays, whether or not the team lost the ball.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="passing_2pt_conversions",
        label="2-Pt Passes",
        full_name="Two-Point Conversion Passes",
        description="Successful two-point conversions thrown.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_pass(
        name="air_epa_total",
        label="Air EPA",
        full_name="Air EPA",
        description=(
            "The share of passing EPA created by the throw itself (distance and placement) "
            "rather than the run after the catch."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_pass(
        name="yac_epa_total",
        label="YAC EPA",
        full_name="Yards-After-Catch EPA",
        description="The share of passing EPA created after the catch by the receivers.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_pass(
        name="xyac_per_completion",
        label="xYAC/Comp",
        full_name="Expected Yards After Catch Per Completion",
        description=(
            "How many yards after the catch an average receiver would have gained on the "
            "same catches, per the nflverse model."
        ),
        shape="avg",
        polarity="neutral",
        source="PBP",
        denominator="completions",
        since=2006,
    ),
    _off_pass(
        name="yac_over_expected_per_completion",
        label="YAC +/-",
        full_name="Yards After Catch Over Expected",
        description="Actual minus expected yards after catch per completion.",
        shape="avg",
        polarity="higher",
        source="PBP",
        denominator="completions",
        since=2006,
    ),
)

OFFENSE_RUSHING_METRICS: tuple[MetricDef, ...] = (
    _off_rush(
        name="rushing_yards",
        label="Rush Yds",
        full_name="Rushing Yards",
        description="Yards gained on the ground, including quarterback runs.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="rushing_epa",
        label="Rush EPA",
        full_name="Rushing EPA",
        description=(
            "Expected points added on rushing plays. Rushing EPA is usually negative "
            "league-wide, so closer to zero (or positive) is good."
        ),
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="rushing_tds",
        label="Rush TDs",
        full_name="Rushing Touchdowns",
        description="Touchdowns scored on the ground.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="rushing_first_downs",
        label="Rush 1Ds",
        full_name="Rushing First Downs",
        description="First downs gained on the ground.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="rushing_fumbles_lost",
        label="Rush Fum Lost",
        full_name="Rushing Fumbles Lost",
        description="Fumbles lost to the defense on rushing plays.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="carries",
        label="Carries",
        full_name="Carries",
        description="Official rushing attempts, including scrambles and kneel-downs.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="designed_carries",
        label="Designed Carries",
        full_name="Designed Carries",
        description="Rushing attempts excluding scrambles and kneel-downs — called runs.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_rush(
        name="yards_per_carry",
        label="Y/C",
        full_name="Yards Per Carry",
        description="Rushing yards divided by carries.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="carries",
        since=1999,
    ),
    _off_rush(
        name="epa_per_carry",
        label="EPA/Carry",
        full_name="EPA Per Carry",
        description="Rushing expected points added per carry — rushing efficiency.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="carries",
        since=1999,
    ),
    _off_rush(
        name="rush_success_rate",
        label="Rush Success %",
        full_name="Rushing Success Rate",
        description="The share of designed runs that improved the team's expected points.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="designed carries",
        since=1999,
    ),
    _off_rush(
        name="explosive_rush_rate",
        label="Explosive Rush %",
        full_name="Explosive Rush Rate",
        description="Runs of 10+ yards divided by carries.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="carries",
        since=1999,
    ),
    _off_rush(
        name="stuffed_run_rate",
        label="Stuffed %",
        full_name="Stuffed Run Rate",
        description="The share of carries stopped for no gain or a loss. Lower is better.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="carries",
        since=1999,
    ),
    _off_rush(
        name="rushing_fumbles",
        label="Rush Fumbles",
        full_name="Rushing Fumbles",
        description="Fumbles on rushing plays, whether or not the team lost the ball.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_rush(
        name="longest_rush",
        label="Long Rush",
        full_name="Longest Rush",
        description="The team's longest run of the season, in yards.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_rush(
        name="rushing_2pt_conversions",
        label="2-Pt Rushes",
        full_name="Two-Point Conversion Rushes",
        description="Successful two-point conversions run in.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
)

OFFENSE_RECEIVING_METRICS: tuple[MetricDef, ...] = (
    _off_recv(
        name="targets",
        label="Targets",
        full_name="Targets",
        description=(
            "Team pass attempts viewed from the receiving side. At team level this is the "
            "same number as pass attempts, shown here for a receiving-flavored view."
        ),
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
        duplicate_of="attempts",
    ),
    _off_recv(
        name="receptions",
        label="Receptions",
        full_name="Receptions",
        description="Team catches — the same number as completions, receiving-side view.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
        duplicate_of="completions",
    ),
    _off_recv(
        name="receiving_yards",
        label="Rec Yds",
        full_name="Receiving Yards",
        description=(
            "Team receiving yards. At team level this equals gross passing yards exactly "
            "(verified against nflverse data)."
        ),
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
        duplicate_of="passing_yards",
    ),
    _off_recv(
        name="receiving_tds",
        label="Rec TDs",
        full_name="Receiving Touchdowns",
        description="Touchdown catches — the same number as passing touchdowns.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
        duplicate_of="passing_tds",
    ),
    _off_recv(
        name="receiving_air_yards",
        label="Rec Air Yds",
        full_name="Receiving Air Yards",
        description="Air yards on targets — the same number as passing air yards.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=2006,
        duplicate_of="passing_air_yards",
    ),
    _off_recv(
        name="receiving_yards_after_catch",
        label="Rec YAC",
        full_name="Receiving Yards After Catch",
        description="Yards gained after the catch — receiving-side view of team YAC.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
        duplicate_of="passing_yards_after_catch",
    ),
    _off_recv(
        name="receiving_first_downs",
        label="Rec 1Ds",
        full_name="Receiving First Downs",
        description="First downs on catches — the same number as passing first downs.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
        duplicate_of="passing_first_downs",
    ),
    _off_recv(
        name="receiving_fumbles",
        label="Rec Fumbles",
        full_name="Receiving Fumbles",
        description="Fumbles by receivers after the catch, whether or not lost.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_recv(
        name="receiving_fumbles_lost",
        label="Rec Fum Lost",
        full_name="Receiving Fumbles Lost",
        description="Fumbles lost to the defense after a catch.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_recv(
        name="catch_rate",
        label="Catch %",
        full_name="Catch Rate",
        description="Receptions divided by targets — the receiving view of completion rate.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="targets",
        since=1999,
        duplicate_of="completion_pct",
    ),
)

OFFENSE_SCORING_METRICS: tuple[MetricDef, ...] = (
    _off_score(
        name="total_tds",
        label="Total TDs",
        full_name="Total Touchdowns",
        description="All touchdowns scored: offense, defense, and special teams.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_score(
        name="offensive_tds",
        label="Off TDs",
        full_name="Offensive Touchdowns",
        description="Passing plus rushing touchdowns.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
        duplicate_of="scrimmage_tds",
    ),
    _off_score(
        name="points_per_drive",
        label="Pts/Drive",
        full_name="Points Per Drive",
        description="Offensive points divided by offensive possessions.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_score(
        name="red_zone_trips",
        label="RZ Trips",
        full_name="Red Zone Trips",
        description="Drives that reached the opponent's 20-yard line.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_score(
        name="red_zone_td_pct",
        label="RZ TD %",
        full_name="Red Zone Touchdown Percentage",
        description="The share of red-zone trips that ended in a touchdown.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="red-zone trips",
        since=1999,
    ),
    _off_score(
        name="points_per_red_zone_trip",
        label="Pts/RZ Trip",
        full_name="Points Per Red Zone Trip",
        description="Points scored on red-zone drives divided by red-zone trips.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="red-zone trips",
        since=1999,
    ),
    _off_score(
        name="goal_to_go_td_pct",
        label="G2G TD %",
        full_name="Goal-To-Go Touchdown Percentage",
        description="Touchdowns divided by goal-to-go situations.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="goal-to-go series",
        since=1999,
    ),
    _off_score(
        name="two_pt_attempts",
        label="2-Pt Att",
        full_name="Two-Point Attempts",
        description="Two-point conversion tries.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
    ),
    _off_score(
        name="two_pt_conversions",
        label="2-Pt Made",
        full_name="Two-Point Conversions",
        description="Successful two-point conversions.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _off_score(
        name="two_pt_conversion_rate",
        label="2-Pt %",
        full_name="Two-Point Conversion Rate",
        description="Successful two-point tries divided by attempts.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="two-point attempts",
        since=1999,
    ),
)

OFFENSE_DOWNS_METRICS: tuple[MetricDef, ...] = (
    _off_downs(
        name="first_downs_penalty",
        label="Penalty 1Ds",
        full_name="First Downs by Penalty",
        description="First downs awarded via defensive penalties.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="third_down_attempts",
        label="3rd Down Att",
        full_name="Third Down Attempts",
        description="Third downs faced by the offense.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="third_down_conversions",
        label="3rd Down Conv",
        full_name="Third Down Conversions",
        description="Third downs converted into a first down or touchdown.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="third_down_pct",
        label="3rd Down %",
        full_name="Third Down Conversion Percentage",
        description="Third downs converted divided by third downs faced.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="third-down attempts",
        since=1999,
    ),
    _off_downs(
        name="third_down_avg_distance",
        label="3rd Down Dist",
        full_name="Average Third Down Distance",
        description=(
            "Average yards to go on third down. Shorter means the offense stays on "
            "schedule on early downs."
        ),
        shape="avg",
        polarity="lower",
        source="PBP",
        denominator="third downs faced",
        since=1999,
    ),
    _off_downs(
        name="fourth_down_attempts",
        label="4th Down Att",
        full_name="Fourth Down Attempts",
        description="Fourth downs the offense went for.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="fourth_down_conversions",
        label="4th Down Conv",
        full_name="Fourth Down Conversions",
        description="Fourth-down tries converted.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="fourth_down_pct",
        label="4th Down %",
        full_name="Fourth Down Conversion Percentage",
        description="Fourth-down tries converted divided by tries.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="fourth-down attempts",
        since=1999,
    ),
    _off_downs(
        name="fourth_down_go_rate",
        label="4th Down Go %",
        full_name="Fourth Down Go Rate",
        description=(
            "How often the team went for it on fourth down instead of kicking. An "
            "aggressiveness style stat."
        ),
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="fourth downs faced",
        since=1999,
    ),
    _off_downs(
        name="fourth_down_aggressiveness",
        label="4th Down Aggr",
        full_name="Fourth Down Aggressiveness",
        description=(
            "Go-for-it rate on fourth-and-short (2 yards or less), where analytics usually "
            "favors going for it."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="fourth-and-short situations",
        since=1999,
    ),
    _off_downs(
        name="series",
        label="Series",
        full_name="Offensive Series",
        description="First-down series the offense ran (each new set of downs).",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_downs(
        name="series_conversion_rate",
        label="Series Conv %",
        full_name="Series Conversion Rate",
        description=(
            "The share of first-down series that gained another first down or scored — a "
            "steadier version of third-down percentage."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="series",
        since=1999,
    ),
    _off_downs(
        name="three_and_out_rate",
        label="3-and-Out %",
        full_name="Three-and-Out Rate",
        description="The share of drives that went three plays and punted. Lower is better.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_downs(
        name="turnovers_on_downs",
        label="TO on Downs",
        full_name="Turnovers on Downs",
        description="Failed fourth-down tries that handed the ball over.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
)

OFFENSE_DRIVES_METRICS: tuple[MetricDef, ...] = (
    _off_drives(
        name="drives",
        label="Drives",
        full_name="Offensive Drives",
        description="Offensive possessions. The denominator for per-drive rates.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _off_drives(
        name="yards_per_drive",
        label="Yds/Drive",
        full_name="Yards Per Drive",
        description="Net yards gained per offensive possession.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="plays_per_drive",
        label="Plays/Drive",
        full_name="Plays Per Drive",
        description="Average number of plays run per possession.",
        shape="avg",
        polarity="neutral",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="time_per_drive",
        label="Time/Drive",
        full_name="Time Per Drive",
        description="Average clock time used per possession.",
        shape="avg",
        polarity="neutral",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="first_downs_per_drive",
        label="1Ds/Drive",
        full_name="First Downs Per Drive",
        description="Average first downs gained per possession.",
        shape="avg",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="score_pct_per_drive",
        label="Score %/Drive",
        full_name="Scoring Rate Per Drive",
        description="The share of possessions ending in any score.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="punt_pct_per_drive",
        label="Punt %/Drive",
        full_name="Punt Rate Per Drive",
        description="The share of possessions ending in a punt. Lower is better.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="turnover_pct_per_drive",
        label="TO %/Drive",
        full_name="Turnover Rate Per Drive",
        description="The share of possessions ending in a giveaway. Lower is better.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="avg_starting_field_position",
        label="Avg Start",
        full_name="Average Starting Field Position",
        description=(
            "Where drives started on average, in yards from the team's own goal line. "
            "Higher means shorter fields to score."
        ),
        shape="avg",
        polarity="higher",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_drives(
        name="long_field_score_pct",
        label="Long-Field Score %",
        full_name="Long-Field Scoring Rate",
        description="Scoring rate on drives that started inside the team's own 25.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="long-field drives",
        since=1999,
    ),
    _off_drives(
        name="drive_penalty_yards",
        label="Drive Pen Yds",
        full_name="Drive Penalty Yards",
        description="Penalty yards assessed against the offense during its drives.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
)

OFFENSE_TURNOVER_METRICS: tuple[MetricDef, ...] = (
    _off_to(
        name="giveaways",
        label="Giveaways",
        full_name="Giveaways",
        description="Interceptions thrown plus fumbles lost.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _off_to(
        name="fumbles",
        label="Fumbles",
        full_name="Fumbles",
        description="All offensive fumbles, whether recovered or lost.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_to(
        name="fumbles_lost",
        label="Fumbles Lost",
        full_name="Fumbles Lost",
        description="Offensive fumbles the defense recovered.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_to(
        name="giveaway_rate_per_offensive_snap",
        label="Giveaway %",
        full_name="Giveaway Rate",
        description="Giveaways divided by offensive snaps. Lower is better.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_to(
        name="giveaways_per_drive",
        label="Giveaways/Drive",
        full_name="Giveaways Per Drive",
        description="Giveaways divided by possessions. Lower is better.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="drives",
        since=1999,
    ),
    _off_to(
        name="turnover_epa",
        label="TO EPA",
        full_name="Turnover EPA",
        description=(
            "Expected points lost on giveaway plays — how costly the turnovers were, not "
            "just how many there were."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
        note="Values are negative; closer to zero means cheaper turnovers.",
    ),
)

OFFENSE_PENALTY_METRICS: tuple[MetricDef, ...] = (
    _off_pen(
        name="penalties",
        label="Penalties",
        full_name="Penalties",
        description="Penalties committed by the team across all units.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_pen(
        name="penalty_yards",
        label="Penalty Yds",
        full_name="Penalty Yards",
        description="Yards assessed against the team on its penalties.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _off_pen(
        name="offensive_penalties",
        label="Off Penalties",
        full_name="Offensive Penalties",
        description="Penalties committed while on offense.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _off_pen(
        name="offensive_penalty_yards",
        label="Off Pen Yds",
        full_name="Offensive Penalty Yards",
        description="Penalty yards assessed while on offense.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _off_pen(
        name="presnap_penalty_rate",
        label="Pre-Snap Pen %",
        full_name="Pre-Snap Penalty Rate",
        description=(
            "False starts, delays of game, and similar self-inflicted penalties per "
            "offensive snap. A discipline measure."
        ),
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
    _off_pen(
        name="penalty_rate_per_offensive_snap",
        label="Off Pen %",
        full_name="Offensive Penalty Rate",
        description="Offensive penalties divided by offensive snaps.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="offensive snaps",
        since=1999,
    ),
)

DEFENSE_METRICS: tuple[MetricDef, ...] = (
    _def_total(
        name="defensive_snaps",
        label="Def Snaps",
        full_name="Defensive Snaps",
        description=(
            "Scrimmage plays the defense was on the field for. The denominator for "
            "per-defensive-snap rates."
        ),
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _def_total(
        name="total_yards_allowed",
        label="Total Yds Allowed",
        full_name="Total Yards Allowed",
        description="Passing plus rushing yards given up by the defense.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
        note="Sums the two allowed yardage stats.",
    ),
    _def_pass(
        name="passing_yards_allowed",
        label="Pass Yds Allowed",
        full_name="Passing Yards Allowed",
        description="Gross passing yards given up through the air.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="passing_epa_allowed",
        label="Pass EPA Allowed",
        full_name="Passing EPA Allowed",
        description=(
            "Expected points added that opposing passing games generated. Negative means "
            "the defense beat an average passing offense."
        ),
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="passing_tds_allowed",
        label="Pass TDs Allowed",
        full_name="Passing Touchdowns Allowed",
        description="Touchdown passes given up.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="passing_first_downs_allowed",
        label="Pass 1Ds Allowed",
        full_name="Passing First Downs Allowed",
        description="First downs given up through the air.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="passing_cpoe_allowed",
        label="CPOE Allowed",
        full_name="Completion Percentage Above Expectation Allowed",
        description=(
            "How much more accurately opponents completed passes than the difficulty of "
            "their throws would predict. Negative means the coverage forced misses."
        ),
        shape="avg",
        polarity="lower",
        source="PBP +TS",
        denominator="opponent pass attempts (model-expected completions)",
        since=2006,
    ),
    _def_rush(
        name="rushing_yards_allowed",
        label="Rush Yds Allowed",
        full_name="Rushing Yards Allowed",
        description="Rushing yards given up on the ground.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_rush(
        name="rushing_epa_allowed",
        label="Rush EPA Allowed",
        full_name="Rushing EPA Allowed",
        description="Expected points added that opposing running games generated.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_rush(
        name="rushing_tds_allowed",
        label="Rush TDs Allowed",
        full_name="Rushing Touchdowns Allowed",
        description="Rushing touchdowns given up.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_rush(
        name="rushing_first_downs_allowed",
        label="Rush 1Ds Allowed",
        full_name="Rushing First Downs Allowed",
        description="First downs given up on the ground.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_press(
        name="def_sacks",
        label="Def Sacks",
        full_name="Defensive Sacks",
        description="Times the defense sacked the opposing quarterback.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_press(
        name="def_qb_hits",
        label="Def QB Hits",
        full_name="Defensive QB Hits",
        description="Times the defense hit the quarterback, beyond sacks.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_press(
        name="def_tackles_for_loss",
        label="Def TFL",
        full_name="Defensive Tackles for Loss",
        description="Tackles made behind the line of scrimmage.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_press(
        name="def_pass_defended",
        label="Def PD",
        full_name="Passes Defended",
        description="Passes broken up or deflected by defenders.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_press(
        name="def_fumbles_forced",
        label="Def FF",
        full_name="Defensive Fumbles Forced",
        description="Fumbles the defense knocked loose.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_press(
        name="def_safeties",
        label="Def Safeties",
        full_name="Defensive Safeties",
        description="Safeties forced by the defense (two points each).",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_to(
        name="def_interceptions",
        label="Def INTs",
        full_name="Defensive Interceptions",
        description="Passes intercepted by the defense.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    # Planned defense expansion (mirrors and defense-only stats).
    _def_total(
        name="first_downs_allowed",
        label="1Ds Allowed",
        full_name="First Downs Allowed",
        description="Total first downs given up by rush, pass, or penalty.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_total(
        name="yards_per_defensive_snap_allowed",
        label="Yds Allowed/Def Snap",
        full_name="Yards Allowed Per Defensive Snap",
        description="Total yards given up divided by defensive snaps.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_total(
        name="epa_per_defensive_snap_allowed",
        label="EPA Allowed/Def Snap",
        full_name="EPA Allowed Per Defensive Snap",
        description="Opponent expected points added per defensive snap.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_total(
        name="success_rate_allowed",
        label="Success % Allowed",
        full_name="Success Rate Allowed",
        description="The share of opponent plays that improved their expected points.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_total(
        name="explosive_play_rate_allowed",
        label="Explosive % Allowed",
        full_name="Explosive Play Rate Allowed",
        description="The share of opponent snaps gaining 20+ pass or 10+ rush yards.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_pass(
        name="attempts_faced",
        label="Att Faced",
        full_name="Pass Attempts Faced",
        description="Official opponent pass attempts against this defense.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="completions_allowed",
        label="Comp Allowed",
        full_name="Completions Allowed",
        description="Opponent passes completed against this defense.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
    ),
    _def_pass(
        name="completion_pct_allowed",
        label="Comp % Allowed",
        full_name="Completion Percentage Allowed",
        description="The share of opponent attempts completed against this defense.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent pass attempts",
        since=1999,
    ),
    _def_pass(
        name="net_passing_yards_allowed",
        label="Net Pass Yds Allowed",
        full_name="Net Passing Yards Allowed",
        description="Passing yards allowed minus opponent sack yardage lost.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pass(
        name="epa_per_dropback_allowed",
        label="EPA/DB Allowed",
        full_name="EPA Per Dropback Allowed",
        description="Opponent passing expected points added per dropback faced.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent dropbacks",
        since=1999,
    ),
    _def_pass(
        name="any_a_allowed",
        label="ANY/A Allowed",
        full_name="Adjusted Net Yards Per Attempt Allowed",
        description=(
            "The best conventional passing stat, from the defense's perspective: what "
            "opposing passers earned per attempt with touchdown, interception, and sack "
            "adjustments."
        ),
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent pass attempts + sacks",
        since=1999,
    ),
    _def_pass(
        name="explosive_pass_rate_allowed",
        label="Expl Pass % Allowed",
        full_name="Explosive Pass Rate Allowed",
        description="Opponent completions of 20+ yards per opponent dropback.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent dropbacks",
        since=1999,
    ),
    _def_pass(
        name="air_yards_allowed",
        label="Air Yds Allowed",
        full_name="Air Yards Allowed",
        description="Total air yards opponents threw for against this defense.",
        shape="count",
        polarity="neutral",
        source="PBP",
        since=2006,
    ),
    _def_pass(
        name="yac_allowed",
        label="YAC Allowed",
        full_name="Yards After Catch Allowed",
        description="Yards opponents gained after the catch — a tackling indicator.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pass(
        name="team_passer_rating_allowed",
        label="Rating Allowed",
        full_name="Passer Rating Allowed",
        description="The classic passer rating opposing quarterbacks combined for.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="official NFL formula over opponent attempts",
        since=1999,
    ),
    _def_pass(
        name="deep_attempt_rate_faced",
        label="Deep Att % Faced",
        full_name="Deep Attempt Rate Faced",
        description="How often opponents attacked this defense deep. A context stat.",
        shape="rate",
        polarity="neutral",
        source="PBP",
        denominator="opponent pass attempts",
        since=1999,
    ),
    _def_rush(
        name="carries_faced",
        label="Carries Faced",
        full_name="Carries Faced",
        description="Opponent rushing attempts against this defense.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
    ),
    _def_rush(
        name="yards_per_carry_allowed",
        label="Y/C Allowed",
        full_name="Yards Per Carry Allowed",
        description="Opponent rushing yards divided by their carries.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent carries",
        since=1999,
    ),
    _def_rush(
        name="rush_success_rate_allowed",
        label="Rush Success % Allowed",
        full_name="Rushing Success Rate Allowed",
        description="The share of opponent designed runs that improved their expected points.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent designed carries",
        since=1999,
    ),
    _def_rush(
        name="explosive_rush_rate_allowed",
        label="Expl Rush % Allowed",
        full_name="Explosive Rush Rate Allowed",
        description="Opponent runs of 10+ yards per opponent carry.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent carries",
        since=1999,
    ),
    _def_recv(
        name="targets_faced",
        label="Targets Faced",
        full_name="Targets Faced",
        description="Opponent pass attempts, receiving-side view of the defense.",
        shape="count",
        polarity="neutral",
        source="PBP +TS",
        since=1999,
        duplicate_of="attempts_faced",
    ),
    _def_recv(
        name="receptions_allowed",
        label="Rec Allowed",
        full_name="Receptions Allowed",
        description="Opponent catches — the same number as completions allowed.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
        duplicate_of="completions_allowed",
    ),
    _def_recv(
        name="receiving_yards_allowed",
        label="Rec Yds Allowed",
        full_name="Receiving Yards Allowed",
        description="Opponent receiving yards — equals passing yards allowed.",
        shape="count",
        polarity="lower",
        source="PBP +TS",
        since=1999,
        duplicate_of="passing_yards_allowed",
    ),
    _def_recv(
        name="catch_rate_allowed",
        label="Catch % Allowed",
        full_name="Catch Rate Allowed",
        description="Opponent receptions per target — receiving view of coverage.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent targets",
        since=1999,
        duplicate_of="completion_pct_allowed",
    ),
    _def_score(
        name="points_per_drive_allowed",
        label="Pts/Drive Allowed",
        full_name="Points Per Drive Allowed",
        description="Points given up per opponent possession.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_score(
        name="red_zone_td_pct_allowed",
        label="RZ TD % Allowed",
        full_name="Red Zone Touchdown Percentage Allowed",
        description="The share of opponent red-zone trips that ended in touchdowns.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent red-zone trips",
        since=1999,
    ),
    _def_score(
        name="goal_to_go_td_pct_allowed",
        label="G2G TD % Allowed",
        full_name="Goal-To-Go Touchdown Percentage Allowed",
        description="Opponent touchdowns per goal-to-go situation faced.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent goal-to-go series",
        since=1999,
    ),
    _def_score(
        name="two_pt_conversion_rate_allowed",
        label="2-Pt % Allowed",
        full_name="Two-Point Conversion Rate Allowed",
        description="Opponent two-point conversion success rate against this defense.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent two-point attempts",
        since=1999,
    ),
    _def_downs(
        name="third_down_pct_allowed",
        label="3rd Down % Allowed",
        full_name="Third Down Percentage Allowed",
        description="Opponent third-down conversion rate against this defense.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent third-down attempts",
        since=1999,
    ),
    _def_downs(
        name="fourth_down_pct_allowed",
        label="4th Down % Allowed",
        full_name="Fourth Down Percentage Allowed",
        description="Opponent fourth-down conversion rate against this defense.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent fourth-down attempts",
        since=1999,
    ),
    _def_downs(
        name="series_conversion_rate_allowed",
        label="Series Conv % Allowed",
        full_name="Series Conversion Rate Allowed",
        description="The share of opponent series that reached a new first down or score.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent series",
        since=1999,
    ),
    _def_downs(
        name="three_and_outs_forced_rate",
        label="3-and-Outs Forced %",
        full_name="Three-and-Outs Forced Rate",
        description="The share of opponent drives forced into three-and-outs.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_drives(
        name="score_pct_per_drive_allowed",
        label="Score %/Drive Allowed",
        full_name="Scoring Rate Per Drive Allowed",
        description="The share of opponent possessions that ended in any score.",
        shape="rate",
        polarity="lower",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_drives(
        name="punts_forced_pct",
        label="Punts Forced %",
        full_name="Punts Forced Rate",
        description="The share of opponent possessions that ended in a punt.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_drives(
        name="avg_starting_field_position_allowed",
        label="Opp Avg Start",
        full_name="Opponent Average Starting Field Position",
        description=(
            "Where opponent drives started on average. Lower (longer fields for them) "
            "is better and reflects special teams and turnover play."
        ),
        shape="avg",
        polarity="lower",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_to(
        name="takeaways",
        label="Takeaways",
        full_name="Takeaways",
        description="Interceptions plus opponent fumbles recovered.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_to(
        name="def_interception_yards",
        label="INT Ret Yds",
        full_name="Interception Return Yards",
        description="Yards gained returning interceptions.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_to(
        name="fumble_recovery_opp",
        label="Opp Fum Rec",
        full_name="Opponent Fumbles Recovered",
        description="Opponent fumbles this defense recovered.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_to(
        name="takeaway_rate_per_defensive_snap",
        label="Takeaway %",
        full_name="Takeaway Rate",
        description="Takeaways divided by defensive snaps.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_to(
        name="takeaways_per_drive",
        label="Takeaways/Drive",
        full_name="Takeaways Per Drive",
        description="Takeaways divided by opponent possessions.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent drives",
        since=1999,
    ),
    _def_to(
        name="takeaway_epa",
        label="Takeaway EPA",
        full_name="Takeaway EPA",
        description="Expected points opponents lost on this defense's takeaway plays.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_to(
        name="def_tds",
        label="Def TDs",
        full_name="Defensive Touchdowns",
        description="Touchdowns scored by the defense on returns.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_to(
        name="fumble_recovery_tds",
        label="Fum Ret TDs",
        full_name="Fumble Return Touchdowns",
        description="Touchdowns scored returning recovered fumbles.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_press(
        name="def_sack_yards",
        label="Sack Yds Forced",
        full_name="Sack Yards Forced",
        description="Yards opponents lost to this defense's sacks.",
        shape="count",
        polarity="higher",
        source="PBP +TS",
        since=1999,
    ),
    _def_press(
        name="def_sack_rate_per_dropback",
        label="Sack Rate Forced",
        full_name="Sack Rate Forced",
        description="Sacks divided by opponent dropbacks — pass-rush efficiency.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent dropbacks",
        since=1999,
    ),
    _def_press(
        name="qb_pressure_events_rate",
        label="Pressure Events %",
        full_name="QB Pressure Events Rate",
        description="Sacks plus quarterback hits divided by opponent dropbacks.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent dropbacks",
        since=1999,
    ),
    _def_press(
        name="stuff_rate",
        label="Stuff %",
        full_name="Run Stuff Rate",
        description="The share of opponent carries stopped for no gain or a loss.",
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="opponent carries",
        since=1999,
    ),
    _def_press(
        name="havoc_rate",
        label="Havoc %",
        full_name="Havoc Rate",
        description=(
            "Disruptive plays — tackles for loss, forced fumbles, interceptions, and pass "
            "breakups — divided by defensive snaps."
        ),
        shape="rate",
        polarity="higher",
        source="PBP",
        denominator="defensive snaps",
        since=1999,
    ),
    _def_press(
        name="defensive_2pt_conversions",
        label="Def 2-Pt",
        full_name="Defensive Two-Point Conversions",
        description="Two-point returns scored by the defense on turnovers during tries.",
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
    _def_pen(
        name="defensive_penalties",
        label="Def Penalties",
        full_name="Defensive Penalties",
        description="Penalties committed while on defense.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pen(
        name="defensive_penalty_yards",
        label="Def Pen Yds",
        full_name="Defensive Penalty Yards",
        description="Penalty yards assessed while on defense.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pen(
        name="defensive_pass_interference",
        label="DPI",
        full_name="Defensive Pass Interference Penalties",
        description="Defensive pass interference penalties committed.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
    _def_pen(
        name="penalty_first_downs_allowed",
        label="Pen 1Ds Gifted",
        full_name="Penalty First Downs Gifted",
        description="Opponent first downs handed over via defensive penalties.",
        shape="count",
        polarity="lower",
        source="PBP",
        since=1999,
    ),
)

SPECIAL_TEAMS_METRICS: tuple[MetricDef, ...] = (
    _special_teams(
        name="st_plays",
        label="ST Plays",
        full_name="Special Teams Plays",
        description=(
            "Special-teams plays where this team had possession: its punts, field goals, and "
            "extra points, plus kickoffs it received."
        ),
        shape="count",
        polarity="neutral",
        source="PBP",
        since=1999,
    ),
    _special_teams(
        name="st_epa",
        label="ST EPA",
        full_name="Special Teams EPA",
        description=(
            "Expected points added on the special-teams plays where this team had possession "
            "(its punts, field goals, and extra points, plus kickoffs it received)."
        ),
        shape="count",
        polarity="higher",
        source="PBP",
        since=1999,
    ),
)

TEAM_METRICS: tuple[MetricDef, ...] = (
    RATING_METRICS
    + OVERALL_METRICS
    + OFFENSE_TOTAL_METRICS
    + OFFENSE_PASSING_METRICS
    + OFFENSE_RUSHING_METRICS
    + OFFENSE_RECEIVING_METRICS
    + OFFENSE_SCORING_METRICS
    + OFFENSE_DOWNS_METRICS
    + OFFENSE_DRIVES_METRICS
    + OFFENSE_TURNOVER_METRICS
    + OFFENSE_PENALTY_METRICS
    + DEFENSE_METRICS
    + SPECIAL_TEAMS_METRICS
)
