import type { PaletteMode, ThemeMode } from '@/api/types'

import PALETTE_DATA from './teamPaletteData.json'

/**
 * Team color palettes. `teamPaletteData.json` is generated by `nfl-sos-ratings team-palettes`
 * (`nfl_sos_ratings/team_palettes.py`) from nflverse team colors, with every accent, hint card,
 * chart color, and heat scale checked for readable contrast in both modes. Page surfaces are never
 * part of a palette, so they stay the same whatever palette shows. This module only reads the file:
 * palette names and groups for the menu, the palette a page shows, the CSS variables a palette sets,
 * its heat scale and logo colors, and every team's two main colors for the team chips.
 */

type Rgb = readonly number[]

/** A heat scale's ends and middle as sRGB channels (0-255). */
export interface HeatScale {
  good: Rgb
  bad: Rgb
  mid: Rgb
}

interface ModeTokens {
  primary: string
  primary_foreground: string
  ring: string
  sidebar_primary: string
  sidebar_primary_foreground: string
  sidebar_ring: string
  chart_1: string
  chart_2: string
  accent: string
  accent_foreground: string
  sidebar_accent: string
  sidebar_accent_foreground: string
  hint: string
  hint_border: string
  heat: HeatScale | null
}

/** The app logo's colors: its tile and the line drawn on it. */
export interface BrandMarkColors {
  background: string
  line: string
}

interface TeamPalette {
  name: string
  conference: string
  division: string
  source: string[]
  mark: BrandMarkColors
  light: ModeTokens
  dark: ModeTokens
}

const PALETTES: Record<string, TeamPalette> = PALETTE_DATA

/** The palette tokens and the CSS variable each one sets. */
const CSS_VARIABLES: Record<Exclude<keyof ModeTokens, 'heat'>, string> = {
  primary: '--primary',
  primary_foreground: '--primary-foreground',
  ring: '--ring',
  sidebar_primary: '--sidebar-primary',
  sidebar_primary_foreground: '--sidebar-primary-foreground',
  sidebar_ring: '--sidebar-ring',
  chart_1: '--chart-1',
  chart_2: '--chart-2',
  accent: '--accent',
  accent_foreground: '--accent-foreground',
  sidebar_accent: '--sidebar-accent',
  sidebar_accent_foreground: '--sidebar-accent-foreground',
  hint: '--hint',
  hint_border: '--hint-border',
}

/** The default palette's logo (`public/favicon.svg`). */
const DEFAULT_MARK: BrandMarkColors = { background: '#1f3a8a', line: '#fb923c' }

/** Every CSS variable a team palette may set, so switching back can clear them all. */
export const PALETTE_CSS_VARIABLES: readonly string[] = Object.values(CSS_VARIABLES)

/** One menu group: a division and its teams, each with its two main brand colors for swatches. */
export interface PaletteGroup {
  division: string
  teams: Array<{ id: string; name: string; colors: string[] }>
}

/** Every team palette grouped by division, in the generated file's (division) order. */
export function paletteGroups(): PaletteGroup[] {
  const groups = new Map<string, PaletteGroup>()
  for (const [id, palette] of Object.entries(PALETTES)) {
    const group = groups.get(palette.division) ?? { division: palette.division, teams: [] }
    group.teams.push({ id, name: palette.name, colors: palette.source })
    groups.set(palette.division, group)
  }
  return [...groups.values()]
}

/** A stored or requested palette as a known one: the old `broncos` is `DEN`, unknown is `classic`. */
export function normalizePalette(value: string | null): PaletteMode {
  if (value === 'broncos') return 'DEN'
  if (value !== null && value in PALETTES) return value
  return 'classic'
}

/**
 * The palette a page shows: on a team or QB page (`pageTeam`), that team's palette while team colors
 * are on and the team has one; everywhere else, and otherwise, the chosen palette.
 */
export function activePalette(chosen: PaletteMode, pageTeam: string | null, teamPageColors: boolean): PaletteMode {
  if (teamPageColors && pageTeam !== null && pageTeam in PALETTES) return pageTeam
  return chosen
}

/** The palette's display name: `Default`, or the team's name. */
export function paletteName(palette: PaletteMode): string {
  return palette === 'classic' ? 'Default' : (PALETTES[palette]?.name ?? 'Default')
}

/** The CSS variables a palette sets in one mode; none for the default palette. */
export function paletteCssVariables(palette: PaletteMode, mode: ThemeMode): Record<string, string> {
  const tokens = palette === 'classic' ? undefined : PALETTES[palette]?.[mode]
  if (!tokens) return {}
  return Object.fromEntries(
    Object.entries(CSS_VARIABLES).map(([token, variable]) => [variable, tokens[token as keyof typeof CSS_VARIABLES]]),
  )
}

/** A team palette's heat scale in one mode, or null for the default palette or its fallback. */
export function heatPaletteFor(palette: PaletteMode, mode: ThemeMode): HeatScale | null {
  if (palette === 'classic') return null
  return PALETTES[palette]?.[mode].heat ?? null
}

/** A team's two main colors (`#RRGGBB`), for its chip beside its name; null for an unknown team. */
export function teamColors(team: string): [string, string] | null {
  const source = PALETTES[team]?.source
  if (!source || source.length === 0) return null
  return [source[0], source[1] ?? source[0]]
}

/** The logo's colors in a palette: the team's for a team palette, the original for the default. */
export function brandMark(palette: PaletteMode): BrandMarkColors {
  return palette === 'classic' ? DEFAULT_MARK : (PALETTES[palette]?.mark ?? DEFAULT_MARK)
}
