import type { PaletteMode, ThemeMode } from '@/api/types'

import PALETTE_DATA from './teamPaletteData.json'

/**
 * Team color palettes. `teamPaletteData.json` is generated by `nfl-sos-ratings team-palettes`
 * (`nfl_sos_ratings/team_palettes.py`) from nflverse team colors, with every accent and chart color
 * checked for readable contrast in both modes; the Broncos palette is the hand-tuned original. This
 * module only reads it: palette names and groups for the menu, the CSS variables a palette sets,
 * and its heat scale.
 */

type Rgb = readonly number[]

/** A heat scale's ends and middle as sRGB channels (0-255). */
export interface HeatScale {
  good: Rgb
  bad: Rgb
  mid: Rgb
}

interface ModeTokens {
  primary: string
  primary_foreground: string
  ring: string
  sidebar_primary: string
  sidebar_primary_foreground: string | null
  sidebar_ring: string
  chart_1: string
  chart_2: string
  heat: HeatScale | null
}

interface TeamPalette {
  name: string
  conference: string
  division: string
  source: string[]
  light: ModeTokens
  dark: ModeTokens
}

const PALETTES: Record<string, TeamPalette> = PALETTE_DATA

/** The palette tokens and the CSS variable each one sets. */
const CSS_VARIABLES: Record<Exclude<keyof ModeTokens, 'heat'>, string> = {
  primary: '--primary',
  primary_foreground: '--primary-foreground',
  ring: '--ring',
  sidebar_primary: '--sidebar-primary',
  sidebar_primary_foreground: '--sidebar-primary-foreground',
  sidebar_ring: '--sidebar-ring',
  chart_1: '--chart-1',
  chart_2: '--chart-2',
}

/** Every CSS variable a team palette may set, so switching back can clear them all. */
export const PALETTE_CSS_VARIABLES: readonly string[] = Object.values(CSS_VARIABLES)

/** One menu group: a division and its teams, each with its two main brand colors for swatches. */
export interface PaletteGroup {
  division: string
  teams: Array<{ id: string; name: string; colors: string[] }>
}

/** Every team palette grouped by division, in the generated file's (division) order. */
export function paletteGroups(): PaletteGroup[] {
  const groups = new Map<string, PaletteGroup>()
  for (const [id, palette] of Object.entries(PALETTES)) {
    const group = groups.get(palette.division) ?? { division: palette.division, teams: [] }
    group.teams.push({ id, name: palette.name, colors: palette.source })
    groups.set(palette.division, group)
  }
  return [...groups.values()]
}

/** A stored or requested palette as a known one: the old `broncos` is `DEN`, unknown is `classic`. */
export function normalizePalette(value: string | null): PaletteMode {
  if (value === 'broncos') return 'DEN'
  if (value !== null && value in PALETTES) return value
  return 'classic'
}

/** The palette's display name: `Default`, or the team's name. */
export function paletteName(palette: PaletteMode): string {
  return palette === 'classic' ? 'Default' : (PALETTES[palette]?.name ?? 'Default')
}

/** The CSS variables a palette sets in one mode; none for the default palette. */
export function paletteCssVariables(palette: PaletteMode, mode: ThemeMode): Record<string, string> {
  const tokens = palette === 'classic' ? undefined : PALETTES[palette]?.[mode]
  if (!tokens) return {}
  return Object.fromEntries(
    Object.entries(CSS_VARIABLES).flatMap(([token, variable]) => {
      const value = tokens[token as keyof typeof CSS_VARIABLES]
      return value === null ? [] : [[variable, value]]
    }),
  )
}

/** A team palette's heat scale in one mode, or null for the default palette or its fallback. */
export function heatPaletteFor(palette: PaletteMode, mode: ThemeMode): HeatScale | null {
  if (palette === 'classic') return null
  return PALETTES[palette]?.[mode].heat ?? null
}
